volumes:
  nextcloud:
  db:

services:

  db:
     image: mariadb:10.6
     restart: always
     command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
     volumes:
       - db:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_PASSWORD=sqlusr
       - MYSQL_DATABASE=nextcloud
       - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=sqlusr
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER:testuser
      - NEXTCLOUD_ADMIN_PASSWORD:1234
      - NEXTCLOUD_TRUSTED_DOMAINS:localhost:8080 172.27.192.1:8080
